name: Build Mod v4
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip and Prepare
        run: |
          unzip scythe-sorting-v4.zip
          # Entra na pasta e dá permissão
          cd scythe-sorting
          chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd scythe-sorting
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scythe-Sorting-v4-JAR
          path: scythe-sorting/build/libs/*.jar
          
